import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

// GmarketSans 폰트
const gmarketSans = localFont({
  src: [
    {
      path: "./fonts/GmarketSansLight.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/GmarketSansMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/GmarketSansBold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-gmarketSans",
  display: "swap", // 페이지가 처음 렌더링될 때 GmarketSans가 로드되지 않으면 기본 폰트로 글자 보여줌
});

// 메타 데이터
export const metadata: Metadata = {
  title: "TRIPLY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${gmarketSans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
